# Generated by Django 5.2.14 on 2026-06-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bloqueado_ate_user_tentativas_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('DIRETOR', 'Diretor'), ('DIRETOR_PEDAGOGICO', 'Diretor Pedagógico'), ('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno'), ('FINANCEIRO', 'Financeiro'), ('SECRETARIA', 'Secretaria')], default='ALUNO', max_length=20),
        ),
    ]
