# Generated by Django 5.2.14 on 2026-06-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('DIRETOR', 'Diretor'), ('DIRETOR_PEDAGOGICO', 'Diretor Pedagogico'), ('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno'), ('FINANCEIRO', 'Financeiro'), ('SECRETARIA', 'Secretaria')], default='ALUNO', max_length=20),
        ),
    ]
