# Generated by Django 5.2.14 on 2026-07-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
