# Generated by Django 5.2.14 on 2026-07-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_verificado_user_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_tentativas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ultimo_envio_otp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
