# Generated by Django 5.2.14 on 2026-07-13 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0028_alter_turma_classe'),
        ('users', '0006_user_otp_codigo_user_otp_expira_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Email Verificado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='academic.escola', verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_codigo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='OTP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expira_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_tentativas',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentativas OTP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('DIRETOR', 'Diretor'), ('DIRETOR_PEDAGOGICO', 'Diretor Pedagógico'), ('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno'), ('FINANCEIRO', 'Financeiro'), ('SECRETARIA', 'Secretaria')], default='ALUNO', max_length=25, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone_verificado',
            field=models.BooleanField(default=False, verbose_name='Telefone Verificado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ultimo_envio_otp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último envio OTP'),
        ),
    ]
