# Generated by Django 5.2.14 on 2026-05-31 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('numero_processo', models.CharField(max_length=20, verbose_name='Número de Processo')),
                ('numero_bi', models.CharField(max_length=20, unique=True, verbose_name='Número do BI')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=15, null=True)),
                ('classe', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_na_turma', models.PositiveIntegerField(blank=True, null=True)),
                ('matricula_confirmada', models.BooleanField(default=False)),
                ('precisa_confirmacao', models.BooleanField(default=False)),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['classe', 'numero_na_turma', 'usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AulaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'Segunda'), ('TER', 'Terça'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta'), ('SAB', 'Sábado')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('tipo', models.CharField(choices=[('AULA', 'Aula'), ('INTERVALO', 'Intervalo')], default='AULA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_validacao', models.CharField(max_length=20, unique=True)),
                ('media_anual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status_final', models.CharField(max_length=20)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('PROVA', 'Prova'), ('EVENTO', 'Evento Escolar'), ('FERIAS', 'Férias'), ('REUNIAO', 'Reunião'), ('PAGAMENTO', 'Pagamento'), ('ENCERRAMENTO', 'Encerramento de Trimestre'), ('NOTA', 'Lançamento de Notas'), ('AVISO', 'Aviso Geral')], max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('evento_geral', models.BooleanField(default=True)),
                ('mostrar_para_diretor', models.BooleanField(default=True)),
                ('mostrar_para_professor', models.BooleanField(default=False)),
                ('mostrar_para_aluno', models.BooleanField(default=False)),
                ('mostrar_para_secretaria', models.BooleanField(default=False)),
                ('enviar_notificacao', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calendário Escolar',
                'verbose_name_plural': 'Calendário Escolar',
                'ordering': ['-prioridade', 'data_inicio', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sistema', models.CharField(default='Gestão Escolar Pro', max_length=200)),
                ('logo_sistema', models.ImageField(blank=True, null=True, upload_to='logos_sistema/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/')),
                ('cor_principal', models.CharField(default='#2563eb', max_length=7)),
                ('cor_secundaria', models.CharField(default='#1e40af', max_length=7)),
                ('ano_letivo_padrao', models.CharField(default='2025/2026', max_length=20)),
                ('bloquear_alteracao_ano', models.BooleanField(default=False)),
                ('ativar_novas_escolas', models.BooleanField(default=True)),
                ('limite_alunos_por_escola', models.IntegerField(default=1000)),
                ('limite_turmas_por_escola', models.IntegerField(default=20)),
                ('plano_padrao', models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium')], default='basico', max_length=20)),
                ('armazenamento_por_escola_mb', models.IntegerField(default=1024)),
                ('moeda', models.CharField(default='Kz', max_length=10)),
                ('valor_mensal_plano_basico', models.DecimalField(decimal_places=2, default=25000, max_digits=10)),
                ('valor_anual_plano_basico', models.DecimalField(decimal_places=2, default=250000, max_digits=10)),
                ('cobranca_automatica', models.BooleanField(default=False)),
                ('login_ativo', models.BooleanField(default=True)),
                ('tempo_sessao_minutos', models.IntegerField(default=120)),
                ('bloqueio_tentativas_login', models.IntegerField(default=5)),
                ('backup_automatico', models.BooleanField(default=True)),
                ('modo_manutencao', models.BooleanField(default=False)),
                ('mensagem_manutencao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_multa_mensalidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_matricula', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_multa_matricula', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_declaracao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_exame', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90, unique=True, verbose_name='Curso')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Escola')),
                ('codigo', models.CharField(blank=True, help_text='Código usado no login da escola', max_length=10, unique=True, verbose_name='Código da Escola')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_escolas/')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('nif', models.CharField(blank=True, help_text='Número de Identificação Fiscal da escola', max_length=14, null=True, verbose_name='NIF')),
                ('email', models.EmailField(blank=True, help_text='Email oficial da escola', max_length=254, null=True, verbose_name='Email da Escola')),
                ('data_expiracao', models.DateField(blank=True, null=True, verbose_name='Data de Expiração do Plano')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoTrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField()),
                ('fechado', models.BooleanField(default=False)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=10)),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('situacao', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('FINALISTA', 'Finalista'), ('TRANSFERIDO', 'Transferido'), ('DESISTENTE', 'Desistente')], max_length=20)),
                ('matricula_confirmada', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ano_letivo__nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=10)),
                ('numero_na_turma', models.PositiveIntegerField(blank=True, null=True)),
                ('matricula', models.CharField(max_length=30)),
                ('total_alunos_turma', models.PositiveIntegerField(default=0, verbose_name='Total de Alunos da Turma')),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Média Final')),
                ('aprovado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Matrícula',
                'verbose_name_plural': 'Históricos de Matrícula',
                'ordering': ['-ano_letivo__nome', 'classe', 'numero_na_turma'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
            options={
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('PAGA', 'Paga'), ('ATRASADA', 'Atrasada')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre')])),
                ('p1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('p2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('exame', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('recurso', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('media', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('situacao', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('RECURSO', 'Recurso')], default='REPROVADO', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['disciplina', 'trimestre'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MENSALIDADE', 'Mensalidade'), ('INSCRICAO', 'Inscrição'), ('UNIFORME', 'Uniforme'), ('EXAME', 'Exame'), ('DECLARACAO', 'Declaração'), ('MULTA', 'Multa'), ('OUTRO', 'Outro')], default='MENSALIDADE', max_length=20)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência'), ('TPA', 'TPA'), ('MULTICAIXA', 'Multicaixa'), ('OUTRO', 'Outro')], max_length=20)),
                ('numero_recibo', models.CharField(blank=True, max_length=30, unique=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('limite_alunos', models.PositiveIntegerField()),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_expiracao', models.DateField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=30)),
                ('classes', models.CharField(help_text='Ex: 10ª, 11ª, 12ª', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_entrega', models.DateField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('ano_letivo', models.CharField(max_length=20)),
                ('fechado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('4', '4ª Classe'), ('5', '5ª Classe'), ('6', '6ª Classe'), ('7', '7ª Classe'), ('8', '8ª Classe'), ('9', '9ª Classe'), ('10', '10ª Classe'), ('11', '11ª Classe'), ('12', '12ª Classe'), ('13', '13ª Classe')], max_length=10, verbose_name='Classe')),
                ('identificador', models.CharField(max_length=5, verbose_name='Identificador')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], default='MANHA', max_length=10, verbose_name='Turno')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
    ]
