# Generated by Django 5.2.14 on 2026-05-31 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'role': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aluno',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='academic.anoletivo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='ultimo_ano_confirmado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_confirmados', to='academic.anoletivo', verbose_name='Último Ano Confirmado'),
        ),
        migrations.AddField(
            model_name='aulahorario',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boletim',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.aluno'),
        ),
        migrations.AddField(
            model_name='calendarioescolar',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to='academic.anoletivo'),
        ),
        migrations.AddField(
            model_name='calendarioescolar',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='academic.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'role': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aulahorario',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.disciplina'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrada',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.escola'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='academic.escola'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='academic.escola'),
        ),
        migrations.AddField(
            model_name='curso',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='academic.escola'),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='escola',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic.escola'),
        ),
        migrations.AddField(
            model_name='calendarioescolar',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to='academic.escola'),
        ),
        migrations.AddField(
            model_name='anoletivo',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anos_letivos', to='academic.escola'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='academic.escola'),
        ),
        migrations.AddField(
            model_name='fechamentotrimestre',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.anoletivo'),
        ),
        migrations.AddField(
            model_name='fechamentotrimestre',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.disciplina'),
        ),
        migrations.AddField(
            model_name='fechamentotrimestre',
            name='fechado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.aluno'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.disciplina'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.escola'),
        ),
        migrations.AddField(
            model_name='historicoacademico',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='academic.aluno'),
        ),
        migrations.AddField(
            model_name='historicoacademico',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.anoletivo'),
        ),
        migrations.AddField(
            model_name='historicoacademico',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.curso'),
        ),
        migrations.AddField(
            model_name='historicomatricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_matriculas', to='academic.aluno'),
        ),
        migrations.AddField(
            model_name='historicomatricula',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.anoletivo'),
        ),
        migrations.AddField(
            model_name='historicomatricula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.curso'),
        ),
        migrations.AddField(
            model_name='horario',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.disciplina'),
        ),
        migrations.AddField(
            model_name='horarioturma',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_escola', to='academic.escola'),
        ),
        migrations.AddField(
            model_name='aulahorario',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='academic.horarioturma'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='academic.aluno'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='academic.anoletivo'),
        ),
        migrations.AddField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academic.aluno'),
        ),
        migrations.AddField(
            model_name='nota',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academic.anoletivo'),
        ),
        migrations.AddField(
            model_name='nota',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academic.disciplina'),
        ),
        migrations.AddField(
            model_name='nota',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academic.escola'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='academic.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='academic.anoletivo', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='academic.escola', verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='mensalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='academic.mensalidade', verbose_name='Mensalidade'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='recebido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagamentoplano',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_plano', to='academic.escola'),
        ),
        migrations.AddField(
            model_name='plano',
            name='escola',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plano_assinatura', to='academic.escola'),
        ),
        migrations.AddField(
            model_name='escola',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escolas', to='academic.plano', verbose_name='Plano'),
        ),
        migrations.AddField(
            model_name='professor',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='academic.escola'),
        ),
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.escola'),
        ),
        migrations.AddField(
            model_name='trimestre',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.escola'),
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='academic.anoletivo', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='academic.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='academic.escola', verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.turma'),
        ),
        migrations.AddField(
            model_name='professor',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='professores', to='academic.turma'),
        ),
        migrations.AddField(
            model_name='horarioturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_turma', to='academic.turma'),
        ),
        migrations.AddField(
            model_name='horario',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academic.turma'),
        ),
        migrations.AddField(
            model_name='historicomatricula',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.turma'),
        ),
        migrations.AddField(
            model_name='historicoacademico',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.turma'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='academic.turma'),
        ),
        migrations.AddField(
            model_name='calendarioescolar',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='academic.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='academic.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='fechamentotrimestre',
            unique_together={('disciplina', 'trimestre', 'ano_letivo')},
        ),
        migrations.AlterUniqueTogether(
            name='mensalidade',
            unique_together={('aluno', 'mes', 'ano_letivo')},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('aluno', 'disciplina', 'trimestre', 'ano_letivo')},
        ),
        migrations.AlterUniqueTogether(
            name='trimestre',
            unique_together={('escola', 'ano_letivo', 'ordem')},
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('classe', 'identificador', 'turno', 'ano_letivo', 'escola', 'curso'), name='unique_turma_por_curso'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplina',
            unique_together={('nome', 'turma', 'escola')},
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['numero_processo'], name='academic_al_numero__0cbdd5_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['numero_bi'], name='academic_al_numero__eef862_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['matricula'], name='academic_al_matricu_6ff797_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['escola'], name='academic_al_escola__3421fe_idx'),
        ),
        migrations.AddIndex(
            model_name='aluno',
            index=models.Index(fields=['ano_letivo'], name='academic_al_ano_let_ad431c_idx'),
        ),
        migrations.AddConstraint(
            model_name='aluno',
            constraint=models.UniqueConstraint(fields=('numero_processo', 'escola'), name='unique_numero_processo_por_escola'),
        ),
        migrations.AddConstraint(
            model_name='aluno',
            constraint=models.UniqueConstraint(fields=('matricula', 'escola'), name='unique_matricula_por_escola'),
        ),
    ]
