# Generated by Django 5.2.14 on 2026-06-04 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to=settings.AUTH_USER_MODEL),
        ),
    ]
