# Generated by Django 5.2.14 on 2026-06-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_disciplina_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentotrimestre',
            name='p1_fechada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fechamentotrimestre',
            name='p2_fechada',
            field=models.BooleanField(default=False),
        ),
    ]
