# Generated by Django 5.2.14 on 2026-06-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_fechamentotrimestre_p1_fechada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechamentotrimestre',
            name='p1_fechada',
        ),
        migrations.RemoveField(
            model_name='fechamentotrimestre',
            name='p2_fechada',
        ),
    ]
