# Generated by Django 5.2.14 on 2026-06-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_fechamentonota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FechamentoNota',
        ),
    ]
