# Generated by Django 5.2.14 on 2026-06-05 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_delete_fechamentonota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField()),
                ('etapa', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('EXAME', 'EXAME')], max_length=10)),
                ('fechado', models.BooleanField(default=False)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.anoletivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.disciplina')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('disciplina', 'trimestre', 'ano_letivo', 'etapa')},
            },
        ),
    ]
