# Generated by Django 5.2.14 on 2026-06-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_alter_nota_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentonota',
            name='etapa',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('EXAME', 'EXAME'), ('RECURSO', 'RECURSO')], max_length=10),
        ),
    ]
