# Generated by Django 5.2.14 on 2026-06-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_alter_fechamentonota_etapa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicomatricula',
            options={'ordering': ['-ano_letivo', 'classe', 'numero_na_turma']},
        ),
        migrations.AlterField(
            model_name='historicomatricula',
            name='media_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicomatricula',
            name='total_alunos_turma',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='historicomatricula',
            unique_together={('aluno', 'ano_letivo')},
        ),
    ]
