# Generated by Django 5.2.14 on 2026-06-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_alter_historicomatricula_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='escola',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Província'),
        ),
    ]
