# Generated by Django 5.2.14 on 2026-06-12 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_escola_municipio_escola_provincia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniPauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('1', '1º Trimestre'), ('2', '2º Trimestre'), ('3', '3º Trimestre')], max_length=1)),
                ('p1', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('p2', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('exame', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('recurso', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_pautas', to='academic.aluno')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_pautas', to='academic.anoletivo')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_pautas', to='academic.disciplina')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_pautas', to='academic.escola')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_pautas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_pautas', to='academic.turma')),
            ],
            options={
                'ordering': ['aluno__numero_na_turma'],
                'unique_together': {('aluno', 'disciplina', 'ano_letivo', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_avaliacao', to='academic.escola')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoMiniPauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mini_pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='academic.minipauta')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.tipoavaliacao')),
            ],
            options={
                'ordering': ['ordem', 'data'],
            },
        ),
    ]
