# Generated by Django 5.2.14 on 2026-06-12 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_minipauta_tipoavaliacao_avaliacaominipauta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoavaliacao',
            name='escola',
        ),
        migrations.AddField(
            model_name='minipauta',
            name='av1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='minipauta',
            name='av2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='minipauta',
            name='av3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='minipauta',
            name='av4',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='minipauta',
            name='av5',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='minipauta',
            name='av6',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='minipauta',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.aluno'),
        ),
        migrations.AlterField(
            model_name='minipauta',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.anoletivo'),
        ),
        migrations.AlterField(
            model_name='minipauta',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.disciplina'),
        ),
        migrations.AlterField(
            model_name='minipauta',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.escola'),
        ),
        migrations.AlterField(
            model_name='minipauta',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='minipauta',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.turma'),
        ),
        migrations.DeleteModel(
            name='AvaliacaoMiniPauta',
        ),
        migrations.DeleteModel(
            name='TipoAvaliacao',
        ),
    ]
