# Generated by Django 5.2.14 on 2026-06-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_remove_tipoavaliacao_escola_minipauta_av1_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='minipauta',
            unique_together={('aluno', 'turma', 'disciplina', 'ano_letivo', 'trimestre')},
        ),
    ]
