# Generated by Django 5.2.14 on 2026-06-16 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_alter_minipauta_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='justificada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='frequencia',
            unique_together={('aluno', 'disciplina', 'data')},
        ),
    ]
