# Generated by Django 5.2.14 on 2026-06-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_frequencia_justificada_frequencia_observacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequencia',
            options={'ordering': ['-data', 'disciplina']},
        ),
    ]
