# Generated by Django 5.2.14 on 2026-06-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_alter_frequencia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('ATRASADA', 'Atrasada')], default='PENDENTE', max_length=20),
        ),
    ]
