# Generated by Django 5.2.14 on 2026-06-17 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0018_alter_mensalidade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulahorario',
            name='escola',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aulahorario',
            name='valor_declaracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aulahorario',
            name='valor_exame',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aulahorario',
            name='valor_matricula',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aulahorario',
            name='valor_mensalidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aulahorario',
            name='valor_multa_matricula',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aulahorario',
            name='valor_multa_mensalidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ConfiguracaoMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_mensalidade', to='academic.curso')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_mensalidade', to='academic.escola')),
            ],
            options={
                'ordering': ['curso__nome', 'classe'],
                'unique_together': {('escola', 'curso', 'classe')},
            },
        ),
    ]
