# Generated by Django 5.2.14 on 2026-06-17 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_aulahorario_escola_aulahorario_valor_declaracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulahorario',
            name='escola',
        ),
        migrations.RemoveField(
            model_name='aulahorario',
            name='valor_declaracao',
        ),
        migrations.RemoveField(
            model_name='aulahorario',
            name='valor_exame',
        ),
        migrations.RemoveField(
            model_name='aulahorario',
            name='valor_matricula',
        ),
        migrations.RemoveField(
            model_name='aulahorario',
            name='valor_mensalidade',
        ),
        migrations.RemoveField(
            model_name='aulahorario',
            name='valor_multa_matricula',
        ),
        migrations.RemoveField(
            model_name='aulahorario',
            name='valor_multa_mensalidade',
        ),
        migrations.DeleteModel(
            name='ConfiguracaoMensalidade',
        ),
    ]
