# Generated by Django 5.2.14 on 2026-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_remove_aulahorario_escola_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='armazenamento_por_escola_mb',
            field=models.PositiveIntegerField(default=1024),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='bloqueio_tentativas_login',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='limite_alunos_por_escola',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='limite_turmas_por_escola',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='plano_padrao',
            field=models.CharField(choices=[('basico', 'Básico'), ('medio', 'Médio'), ('premium', 'Premium')], default='basico', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='tempo_sessao_minutos',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
