# Generated by Django 5.2.14 on 2026-06-18 14:53

import academic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_alter_configuracao_armazenamento_por_escola_mb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='bloquear_alteracao_ano',
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='ano_letivo_padrao',
            field=models.CharField(blank=True, default=academic.models.get_ano_letivo_atual, max_length=20, null=True),
        ),
    ]
