# Generated by Django 5.2.14 on 2026-06-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_remove_configuracao_bloquear_alteracao_ano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='data_expiracao',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='escola',
        ),
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
