# Generated by Django 5.2.14 on 2026-06-20 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0024_auto_20260620_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoplano',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pagamentoplano',
            name='mes_referencia',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamentoplano',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamentoplano',
            name='plano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='academic.plano'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagamentoplano',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_planos', to='academic.escola'),
        ),
    ]
