# Generated by Django 5.2.14 on 2026-06-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0025_pagamentoplano_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracaofinanceira',
            old_name='valor_mensalidade',
            new_name='valor_mensalidade_1',
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_11',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_12',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_13',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_9',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_iniciacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
