# Generated by Django 5.2.14 on 2026-07-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0027_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='classe',
            field=models.CharField(choices=[('0', 'Iniciação'), ('1', '1ª Classe'), ('2', '2ª Classe'), ('3', '3ª Classe'), ('4', '4ª Classe'), ('5', '5ª Classe'), ('6', '6ª Classe'), ('7', '7ª Classe'), ('8', '8ª Classe'), ('9', '9ª Classe'), ('10', '10ª Classe'), ('11', '11ª Classe'), ('12', '12ª Classe'), ('13', '13ª Classe')], max_length=10, verbose_name='Classe'),
        ),
    ]
