# Generated by Django 5.2.14 on 2026-07-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0028_alter_turma_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='nome_sistema',
            field=models.CharField(default='EdusCel', max_length=200),
        ),
    ]
