# Generated by Django 5.2.14 on 2026-07-16 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0029_alter_configuracao_nome_sistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='sala',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='identificador',
            field=models.CharField(max_length=5, verbose_name='Identificador da Turma'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável'),
        ),
    ]
