# Generated by Django 5.2.14 on 2026-07-17 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0030_turma_sala_alter_turma_identificador_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioturma',
            options={'ordering': ['-ano_letivo__nome', 'turma__classe', 'turma__identificador']},
        ),
        migrations.AddField(
            model_name='horarioturma',
            name='ano_letivo',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academic.anoletivo', verbose_name='Ano Letivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horarioturma',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='horarioturma',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Horário bloqueado'),
        ),
        migrations.AlterUniqueTogether(
            name='horarioturma',
            unique_together={('escola', 'ano_letivo', 'turma', 'turno')},
        ),
    ]
