# Generated by Django 5.2.14 on 2026-07-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0031_alter_horarioturma_options_horarioturma_ano_letivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='diretor_turma',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_como_diretor', to=settings.AUTH_USER_MODEL, verbose_name='Diretor de Turma'),
        ),
    ]
