# Generated by Django 5.2.14 on 2026-07-17 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0032_turma_diretor_turma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='coordenador',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_coordenados', to=settings.AUTH_USER_MODEL, verbose_name='Coordenador do Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=90, verbose_name='Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nome', 'escola')},
        ),
    ]
