# Generated by Django 5.2.14 on 2026-07-19 16:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0033_curso_coordenador_alter_curso_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='aplicar_multa_atraso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='dia_vencimento',
            field=models.PositiveIntegerField(default=10, help_text='Dia limite para pagamento da mensalidade'),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='email_financeiro',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='moeda',
            field=models.CharField(default='Kz', max_length=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='mostrar_logo_recibo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='nome_assinatura',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='percentual_desconto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual de desconto permitido', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='permitir_pagamento_atrasado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='telefone_financeiro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='texto_rodape_recibo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaofinanceira',
            name='escola',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_financeira', to='academic.escola'),
        ),
    ]
