# Generated by Django 5.2.14 on 2026-07-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0034_configuracaofinanceira_aplicar_multa_atraso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracaofinanceira',
            old_name='nome_assinatura',
            new_name='titular_conta',
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='avisar_despesa_alta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='avisar_mensalidade_vencida',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='avisar_pagamento_recebido',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='dias_tolerancia',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='endereco_financeiro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='formato_relatorio',
            field=models.CharField(default='PDF', max_length=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='formato_valor',
            field=models.CharField(default='1.500 Kz', max_length=30),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='mostrar_assinatura',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='mostrar_carimbo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='mostrar_comparacao',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='mostrar_graficos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='mostrar_saldo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='nif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='nome_recibo',
            field=models.CharField(default='Recibo', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='numero_conta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='numero_inicial_recibo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='percentual_juro_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='prefixo_recibo',
            field=models.CharField(default='REC', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracaofinanceira',
            name='dia_vencimento',
            field=models.PositiveIntegerField(default=10, help_text='Dia limite para pagamento'),
        ),
        migrations.AlterField(
            model_name='configuracaofinanceira',
            name='percentual_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
