# Generated by Django 5.2.14 on 2026-07-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0035_rename_nome_assinatura_configuracaofinanceira_titular_conta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_mensalidades', to='academic.escola')),
            ],
            options={
                'verbose_name': 'Configuração de Mensalidade',
                'verbose_name_plural': 'Configurações de Mensalidades',
                'ordering': ['classe'],
                'constraints': [models.UniqueConstraint(fields=('escola', 'classe'), name='unique_mensalidade_escola_classe')],
            },
        ),
    ]
