# Generated by Django 5.2.14 on 2026-07-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0036_configuracaomensalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_1',
        ),
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_10',
        ),
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_11',
        ),
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_12',
        ),
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_13',
        ),
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_2',
        ),
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_3',
        ),
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_4',
        ),
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_5',
        ),
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_6',
        ),
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_7',
        ),
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_8',
        ),
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_9',
        ),
        migrations.RemoveField(
            model_name='configuracaofinanceira',
            name='valor_mensalidade_iniciacao',
        ),
        migrations.AlterField(
            model_name='configuracaofinanceira',
            name='dia_vencimento',
            field=models.PositiveIntegerField(default=10, help_text='Dia limite para pagamento da mensalidade'),
        ),
    ]
