# Generated by Django 5.2.14 on 2026-07-19 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0037_remove_configuracaofinanceira_valor_mensalidade_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaomensalidade',
            options={'ordering': ['ordem', 'classe'], 'verbose_name': 'Configuração de Mensalidade', 'verbose_name_plural': 'Configurações de Mensalidades'},
        ),
        migrations.RemoveConstraint(
            model_name='configuracaomensalidade',
            name='unique_mensalidade_escola_classe',
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='swift',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_certificado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_historico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='valor_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaomensalidade',
            name='aplicar_multa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaomensalidade',
            name='curso',
            field=models.ForeignKey(blank=True, help_text='Opcional. Utilize quando a escola possuir cursos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_mensalidades', to='academic.curso', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='configuracaomensalidade',
            name='dia_vencimento',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='configuracaomensalidade',
            name='dias_tolerancia',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='configuracaomensalidade',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracaomensalidade',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Utilizado para ordenar as classes corretamente.'),
        ),
        migrations.AddField(
            model_name='configuracaomensalidade',
            name='percentual_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaomensalidade',
            name='percentual_juros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracaomensalidade',
            name='valor_multa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracaofinanceira',
            name='dia_vencimento',
            field=models.PositiveIntegerField(default=10, help_text='Dia padrão de vencimento das mensalidades.'),
        ),
        migrations.AlterField(
            model_name='configuracaofinanceira',
            name='formato_valor',
            field=models.CharField(default='1.500,00 Kz', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='configuracaomensalidade',
            constraint=models.UniqueConstraint(condition=models.Q(('curso__isnull', False)), fields=('escola', 'curso', 'classe'), name='unique_mensalidade_escola_curso_classe'),
        ),
        migrations.AddConstraint(
            model_name='configuracaomensalidade',
            constraint=models.UniqueConstraint(condition=models.Q(('curso__isnull', True)), fields=('escola', 'classe'), name='unique_mensalidade_escola_classe'),
        ),
    ]
