# Generated by Django 5.2.14 on 2026-07-20 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0038_alter_configuracaomensalidade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaomensalidade',
            options={'ordering': ['ordem', 'classe', 'curso__nome'], 'verbose_name': 'Configuração de Mensalidade', 'verbose_name_plural': 'Configurações de Mensalidades'},
        ),
        migrations.RemoveConstraint(
            model_name='configuracaomensalidade',
            name='unique_mensalidade_escola_curso_classe',
        ),
        migrations.RemoveConstraint(
            model_name='configuracaomensalidade',
            name='unique_mensalidade_escola_classe',
        ),
        migrations.AlterField(
            model_name='configuracaomensalidade',
            name='classe',
            field=models.CharField(choices=[('0', 'Iniciação'), ('1', '1ª Classe'), ('2', '2ª Classe'), ('3', '3ª Classe'), ('4', '4ª Classe'), ('5', '5ª Classe'), ('6', '6ª Classe'), ('7', '7ª Classe'), ('8', '8ª Classe'), ('9', '9ª Classe'), ('10', '10ª Classe'), ('11', '11ª Classe'), ('12', '12ª Classe'), ('13', '13ª Classe')], max_length=10, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='configuracaomensalidade',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_mensalidades', to='academic.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='configuracaomensalidade',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='configuracaomensalidade',
            constraint=models.UniqueConstraint(fields=('escola', 'curso', 'classe'), name='unique_config_mensalidade_escola_curso_classe'),
        ),
    ]
