# Generated by Django 5.2.14 on 2026-07-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0039_alter_configuracaomensalidade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaomensalidade',
            name='classe',
            field=models.CharField(choices=[], max_length=10, verbose_name='Classe'),
        ),
    ]
