# Generated by Django 5.2.14 on 2026-07-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0041_alter_configuracaomensalidade_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='responsavel_financeiro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
