# Generated by Django 5.2.14 on 2026-07-20 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0042_configuracaofinanceira_email_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoMultaJuros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicar_multa', models.BooleanField(default=False)),
                ('tipo_multa', models.CharField(choices=[('FIXA', 'Valor Fixo'), ('PERCENTUAL', 'Percentual')], default='FIXA', max_length=20)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dias_tolerancia', models.PositiveIntegerField(default=5)),
                ('percentual_juros', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_multa_juros', to='academic.escola')),
            ],
        ),
    ]
