# Generated by Django 5.2.14 on 2026-07-21 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0043_configuracaomultajuros'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=120)),
                ('titular', models.CharField(max_length=200)),
                ('iban', models.CharField(max_length=80)),
                ('numero_conta', models.CharField(max_length=80)),
                ('swift', models.CharField(blank=True, max_length=30)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_bancos/')),
                ('ativa', models.BooleanField(default=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.escola')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('padrao', models.BooleanField(default=False)),
                ('exige_comprovativo', models.BooleanField(default=False)),
                ('permite_troco', models.BooleanField(default=False)),
                ('permite_pagamento_parcial', models.BooleanField(default=True)),
                ('cobra_taxa', models.BooleanField(default=False)),
                ('percentual_taxa', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pagamento', to='academic.escola')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
