# Generated by Django 5.2.14 on 2026-07-21 11:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0044_contabancaria_metodopagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contabancaria',
            options={'ordering': ['banco', 'titular'], 'verbose_name': 'Conta Bancária', 'verbose_name_plural': 'Contas Bancárias'},
        ),
        migrations.AlterModelOptions(
            name='metodopagamento',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Método de Pagamento', 'verbose_name_plural': 'Métodos de Pagamento'},
        ),
        migrations.AlterUniqueTogether(
            name='metodopagamento',
            unique_together={('escola', 'codigo')},
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='numero_telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone associado'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='metodopagamento',
            name='cor',
            field=models.CharField(default='#2563eb', max_length=20, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='metodopagamento',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='metodopagamento',
            name='icone',
            field=models.CharField(default='bi-credit-card', max_length=50, verbose_name='Ícone Bootstrap'),
        ),
        migrations.AddField(
            model_name='metodopagamento',
            name='metodo_padrao',
            field=models.BooleanField(default=False, verbose_name='Método padrão'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='banco',
            field=models.CharField(max_length=150, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_bancarias', to='academic.escola', verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='iban',
            field=models.CharField(blank=True, max_length=100, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='numero_conta',
            field=models.CharField(blank=True, max_length=80, verbose_name='Número da Conta'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='financeiro/qr_codes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='swift',
            field=models.CharField(blank=True, max_length=50, verbose_name='SWIFT'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='titular',
            field=models.CharField(max_length=200, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='cobra_taxa',
            field=models.BooleanField(default=False, verbose_name='Cobrar taxa'),
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pagamento', to='academic.escola', verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='exige_comprovativo',
            field=models.BooleanField(default=False, verbose_name='Exigir comprovativo'),
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='ordem',
            field=models.PositiveIntegerField(default=1, verbose_name='Ordem de exibição'),
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='percentual_taxa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual da taxa (%)'),
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='permite_pagamento_parcial',
            field=models.BooleanField(default=True, verbose_name='Permitir pagamento parcial'),
        ),
        migrations.AlterField(
            model_name='metodopagamento',
            name='permite_troco',
            field=models.BooleanField(default=False, verbose_name='Permitir troco'),
        ),
        migrations.RemoveField(
            model_name='metodopagamento',
            name='padrao',
        ),
    ]
