# Generated by Django 5.2.14 on 2026-07-21 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0045_alter_contabancaria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='academic.metodopagamento', verbose_name='Forma de Pagamento'),
        ),
    ]
