# Generated by Django 5.2.14 on 2026-07-21 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0047_auto_20260721_1343'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='taxa_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa (%)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='taxa_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor da Taxa'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='total_recebido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Recebido'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='academic.metodopagamento', verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo',
            field=models.CharField(choices=[('MENSALIDADE', 'Mensalidade'), ('INSCRICAO', 'Inscrição'), ('UNIFORME', 'Uniforme'), ('EXAME', 'Exame'), ('DECLARACAO', 'Declaração'), ('MULTA', 'Multa'), ('OUTRO', 'Outro')], default='MENSALIDADE', max_length=30),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Pago'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['escola', 'tipo'], name='academic_pa_escola__277f54_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['aluno', 'criado_em'], name='academic_pa_aluno_i_30d2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['numero_recibo'], name='academic_pa_numero__680533_idx'),
        ),
    ]
