# Generated by Django 5.2.14 on 2026-07-21 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0048_pagamento_taxa_percentual_pagamento_taxa_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=150)),
                ('numero_conta', models.CharField(blank=True, max_length=50, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('agencia', models.CharField(blank=True, max_length=50, null=True)),
                ('moeda', models.CharField(default='AOA', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bancarios', to='academic.escola')),
            ],
        ),
    ]
