# Generated by Django 5.2.14 on 2026-07-21 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0049_dadosbancarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosbancarios',
            name='tipo_conta',
            field=models.CharField(choices=[('PRINCIPAL', 'Conta Principal'), ('MENSALIDADES', 'Recebimento de Mensalidades'), ('SALARIOS', 'Pagamento de Salários'), ('OUTRA', 'Outra')], default='PRINCIPAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bancarios', to='academic.escola'),
        ),
    ]
